-- 코드를 작성해주세요
SELECT 
    CONCAT(QUARTER, 'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT 
        EXTRACT(QUARTER FROM DIFFERENTIATION_DATE) AS QUARTER
    FROM 
        ECOLI_DATA
) AS SUBQUERY
GROUP BY QUARTER
ORDER BY QUARTER;
