-- 코드를 입력하세요
# SELECT ID, NAME, HOST_ID
# FROM PLACES
# WHERE HOST_ID IN (
#     SELECT HOST_ID 
#     FROM PLACES 
#     GROUP BY HOST_ID 
#     HAVING COUNT(*) >= 2
# )
# ORDER BY ID ASC;

SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
JOIN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
) AS FILTERED 
    ON P.HOST_ID = FILTERED.HOST_ID
ORDER BY P.ID ASC;
