-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS MAX_PRICE_PER_CATEGORY
ON FP.CATEGORY = MAX_PRICE_PER_CATEGORY.CATEGORY
AND FP.PRICE = MAX_PRICE_PER_CATEGORY.MAX_PRICE
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
